name: Build and Upload nightly game builds

on:
  workflow_dispatch:
    inputs:
      build-defines:
        type: string
        description: Build defines to use
        default: '-DGITHUB_BUILD -DFEATURE_POLYMOD_MODS -DREDIRECT_ASSETS_FOLDER -DFEATURE_DISCORD_RPC -DFEATURE_VIDEO_PLAYBACK -DFEATURE_SCREENSHOTS -DFEATURE_CHART_EDITOR -DFEATURE_STAGE_EDITOR -DFEATURE_GHOST_TAPPING'
      save-artifact:
        type: boolean
        description: Save the build artifact to Github Actions
        default: true
  push:

jobs:
  build-game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1 # Saves massive amounts of RAM/Disk

      - name: Create Swap Space (Critical for V-Slice)
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install System Dependencies (Video/Audio)
        # Without these, hxvlc and lime will crash during the "Build Game" step
        run: |
          sudo apt-get update
          sudo apt-get install libvlc-dev libvlccore-dev -y

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install HMM and Dependencies
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          # Use the full path to hmm to ensure it runs
          haxelib run hmm install
          haxelib run lime setup
          haxelib run lime setup flixel

      - name: Build game (HTML5)
        env:
          # Tell Haxe to use more memory before it panics
          HAXE_FIXED_ADDRESS: 0x40000000 
        run: |
          # Use 'lime build html5' directly. 
          # We remove the '--times' to keep the log clean so it doesn't freeze the browser.
          haxelib run lime build html5 -release ${{ github.event.inputs.build-defines || '-DGITHUB_BUILD -DFEATURE_POLYMOD_MODS -DREDIRECT_ASSETS_FOLDER -DFEATURE_DISCORD_RPC -DFEATURE_VIDEO_PLAYBACK -DFEATURE_SCREENSHOTS -DFEATURE_CHART_EDITOR -DFEATURE_STAGE_EDITOR -DFEATURE_GHOST_TAPPING' }}
        timeout-minutes: 120

      - name: Save build artifact
        if: ${{ github.event.inputs.save-artifact || true }}
        uses: actions/upload-artifact@v4
        with:
          name: FNF-VSlice-Build-HTML5
          path: export/release/html5/bin/
